### ISSUE TITLE
cannot download all blocks

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/ads#150]
Test network was working for about one week. I called `get_blocks` function. Only 564 blocks were updated. First block was genesis block. I updated blocks from 5B72D000 to 5B773600, while current block time was 5B7C2A00. Concurrent `get_blocks` calls didn't update further blocks. 564 blocks translates to less than 3,5 day. This means that I am not able to update all blocks.

**Comment by lenter83** [comment]
The problem is related to restarting of the node. If for some reason there is at least one block in history that doesn't have required number of signatures then get_blocks is stuck on this block and never downloads more blocks.

**Comment by lenter83** [comment]
Resolved in v1.0.1
