### ISSUE TITLE
Invalid change_node_key response for remote node

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/ads#158]
If function `change_node_key` is called with node parameter different than user node, response is invalid. When node exists reponse has `result` field with text `Node key changed`.

If node doesn't exist error message is `Setting key for remote bank failed`, which is correct behaviour.

**Comment by lenter83** [comment]
Setting remote node key is a valid operation only on a node that is in double-spent state. Client should check for this condition before accepting transaction.
