### ISSUE TITLE
create_account: unexpected data while decoding tx.data

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/ads#163]
Field `tx.data` has unexpected string `00000000` (4 bytes) after node in which account should be created. What data is stored in this 4 bytes? Are they needed?

```
06 type
  0100 node src
      00000000 user src
	          04000000 msid
			          AB989B5B time
					          0100 node dest
							      00000000 ??
								          A9C0D972D8AAB73805EC4A28291E052E3B5FAFE0ADC9D724917054E5E2690363 public key
```

**Comment by lenter83** [comment]
This is account number. It is only used when create_account assigns previously used account number (this can happen if previous account was deleted)
