### ISSUE TITLE
Merge esc-qa with esc repo

### ISSUE THREAD

**Issue by m-pilarczyk** [adshares/ads#23]
<a href="https://github.com/m-pilarczyk"><img src="https://avatars3.githubusercontent.com/u/10977239?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [m-pilarczyk](https://github.com/m-pilarczyk)**
_Thursday May 10, 2018 at 12:34 GMT_
_Originally opened as https://github.com/adshares/esc/issues/19_

----

**Comment by m-pilarczyk** [comment]
<a href="https://github.com/PawelPodkalicki"><img src="https://avatars2.githubusercontent.com/u/38037054?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PawelPodkalicki](https://github.com/PawelPodkalicki)**
_Monday May 14, 2018 at 16:27 GMT_

----

https://github.com/adshares/esc/wiki/QA-tests

**Comment by PawelPodkalicki** [comment]
Outdated.
