### ISSUE TITLE
add test case for status functions

### ISSUE THREAD

**Issue by m-pilarczyk** [adshares/ads#46]
<a href="https://github.com/PawelPodkalicki"><img src="https://avatars2.githubusercontent.com/u/38037054?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PawelPodkalicki](https://github.com/PawelPodkalicki)**
_Tuesday May 22, 2018 at 12:13 GMT_
_Originally opened as https://github.com/adshares/esc/issues/42_

----

Add test cases for:
- set_account_status,
- set_node_status,
- unset_account_status,
- unset_node_status.

**Comment by PawelPodkalicki** [comment]
Tests for set_account_status, unset_account_status are ready.
