### ISSUE TITLE
after retrieve_funds from main account - new events are appended to log

### ISSUE THREAD

**Issue by m-pilarczyk** [adshares/ads#51]
<a href="https://github.com/PawelPodkalicki"><img src="https://avatars2.githubusercontent.com/u/38037054?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PawelPodkalicki](https://github.com/PawelPodkalicki)**
_Monday May 28, 2018 at 10:44 GMT_
_Originally opened as https://github.com/adshares/esc/issues/47_

----

I retrieved funds from main account. After successfull operation it had balance equal 0. 
After some block periods I checked log for this account. There was difference between account balance and sum of events in log. That was because after retrieve_funds new events was appended to log, while balance didn't become negative.

Should account be deleted in that case?

**Comment by PawelPodkalicki** [comment]
Fixed in b2d99d13ae0624650920b9b2deaa0beae463ba35

When balance is 0, next events have 0 amount.
