### ISSUE TITLE
create_account: what is valid format of node id?

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/ads#64]
From my observation create_account function takes `node` parameter as integer. 

- When I passed "F", account was created in local node. 
- When I passed non-existing node "10", function respond with an error "Bad timing for remote account request, try again later.".

Please, confirm valid format of `node` parameter, and I will update wiki.

**Comment by awlodarkiewicz** [comment]
Genesis generated node id is in hex (eg. 000A). The hex values is used in account identifiers, but can't be used in the svid options.cfg parameter. Works when you change it to integer (eg. 0010).

**Comment by PawelPodkalicki** [comment]
Wiki updated in https://github.com/adshares/ads/wiki/Home/8ab8aec354e5798e575e5589fca0a5c4688bb205
