### ISSUE TITLE
incorrect response format while "Connection refused"

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/ads#81]
Connection refused response is returned multiline (with line breaks) even if --nice parameter is set to 0 (-n0 is set).
```
{
    "error": "Connection refused"
}
```

**Comment by PawelPodkalicki** [comment]
The same for `read: End of file error`. Error occurs in response for get_blocks request when all blocks were already updated.
```
{
    "error": "read: End of file"
}
```

**Comment by lenter83** [comment]
fixed
